import Banner from "../banner/Banner"
const MovieSection = () => {
  return (
    <>
    <Banner/>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quisquam molestias quibusdam repellat aut quis, libero animi temporibus, natus laboriosam dicta perspiciatis aspernatur voluptate debitis, officia consectetur omnis laudantium ea.</p>
    </>
  )
}

export default MovieSection